#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
xrandr -r 75 &
xset r rate 200 38 &
setxkbmap -option "caps:swapescape" &
picom --experimental-backends &
# ~/.config/polybar/launch.sh --shapes &
wal -R

bspc monitor -d I II III IV V

bspc config focused_border_color \#fca817
bspc config normal_border_color  \#35701c
bspc config border_width         4
bspc config window_gap           8

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# bspc rule -a Gimp desktop='^8' state=floating follow=on
# bspc rule -a Chromium desktop='^2'
# bspc rule -a mplayer2 state=floating
# bspc rule -a Kupfer.py focus=on
# bspc rule -a Screenkey manage=off

# rustyvibes ~/Downloads/Soundpacks/Soundpacks/cherrymx-brown-pbt
